
export const reasonOptions = [
    { value: 'Business', label:'For Business'},
    { value: 'Dealership', label: 'For Dealership' },
    { value: 'Transport', label: 'For Transport' },
  ];

  export const categoryOptions=[
    { value: 'Quality A', label:'Quality A'},
    { value: 'Quality B', label: 'Quality B' },
    { value: 'Quality C', label: 'Quality C' },
    { value: 'Quality D', label: 'Quality D' },
  ]

  export const typeOptions=[
    { value: 'Internal', label:'Internal'},
    { value: 'External', label: 'External' },
    { value: 'Vendor', label: 'Vendor' },
  ];

  export const priorityOptions=[
    { value: 'Low', label:'Low'},
    { value: 'Medium', label: 'Medium' },
    { value: 'High', label: 'High' },
  ]

  export const divisonOptions=[
    { value: 'Compressor', label:'Compressor'},
    { value: 'Filters', label: 'Filters' },
    { value: 'Pumps', label: 'Pumps' },
    { value: 'Glass', label: 'Glass' },
    { value: 'Water Heater', label: 'Water Heater' },
  ]
  export const deapartMentOptions=[
    { value: 'Startegy', label:'Startegy'},
    { value: 'Finance', label: 'Finance' },
    { value: 'Quality', label: 'Quality' },
    { value: 'Maintainance', label: 'Maintainance' },
    { value: 'Stores', label: 'Stores' },
  ]
  export const locationOptions=[
    { value: 'Pune', label:'Pune'},
    { value: 'Delhi', label: 'Delhi' },
    { value: 'Mumbai', label: 'Mumbai' },
  ]

  export const initialFormValues={
    reason: reasonOptions[0].value,
    type: typeOptions[0].value,
    division: divisonOptions[0].value,
    category: categoryOptions[0].value,
    priority: priorityOptions[0].value,
    department: deapartMentOptions[0].value,
    location: locationOptions[0].value,
  }


  export const projects=[
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter2",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
    {project_name:"Line Filter",reason:"Business" ,
    type:"Internal",
    division:"Filters",
    category:"Quality",
    priority:"High",
    department:"Quality",
    location:"Pune",
    status:"Running",
    endDate:"Jun-21,2020",
    startDate:"Jan-01,2021"
    },
   
  ]


  